### ISSUE TITLE
Typo ("libray") in README.md

### ISSUE THREAD

**Issue by PhysicistSouravDas** [terrible-coder/multivariate_calculus#31]
Should be `library`.

`4: A zero dependency libray that handles calculus of several variables in`

**Comment by terrible-coder** [comment]
Thank you @PhysicistSouravDas
The typo has been fixed in commit fdf31b7a48793cad41a7cc6107fff0df2ade6f52

**Comment by terrible-coder** [comment]
Thank you @PhysicistSouravDas
The type has been fixed in commit fdf31b7a48793cad41a7cc6107fff0df2ade6f52
